export const FETCH_USERSLIST_SUCCESFUL = `FETCH_USERSLIST_SUCCESFUL`;
export const GET_FULL_USER_SUCCES = `GET_FULL_USER_SUCCES`;
export const GET_TOTAL_USER_STARS_SUCCES = `GET_TOTAL_USER_STARS_SUCCES`;
export const FETCH_USERLIST_ERROR = `FETCH_USERLIST_ERROR`;